// Code generated by Kitex v0.6.1. DO NOT EDIT.

package mainstoreservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	mainstore "github.com/tankpanv/demo/store/kitex_gen/wealth/stock/mainstore"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ItemDetail(ctx context.Context, req *mainstore.ItemDetailReq, callOptions ...callopt.Option) (r *mainstore.ItemDetailResp, err error)
	MainPage(ctx context.Context, req *mainstore.MainPageReq, callOptions ...callopt.Option) (r *mainstore.MainPageResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kMainstoreServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kMainstoreServiceClient struct {
	*kClient
}

func (p *kMainstoreServiceClient) ItemDetail(ctx context.Context, req *mainstore.ItemDetailReq, callOptions ...callopt.Option) (r *mainstore.ItemDetailResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ItemDetail(ctx, req)
}

func (p *kMainstoreServiceClient) MainPage(ctx context.Context, req *mainstore.MainPageReq, callOptions ...callopt.Option) (r *mainstore.MainPageResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MainPage(ctx, req)
}
