// Code generated by Kitex v0.6.1. DO NOT EDIT.

package strategyservice

import (
	server "github.com/cloudwego/kitex/server"
	strategy "github.com/tankpanv/demo/store/kitex_gen/federation/recommend/strategy"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler strategy.StrategyService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
