// Code generated by Kitex v0.6.1. DO NOT EDIT.
package strategyservice

import (
	server "github.com/cloudwego/kitex/server"
	strategy "github.com/tankpanv/demo/store/kitex_gen/federation/recommend/strategy"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler strategy.StrategyService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
