// Code generated by Kitex v0.6.1. DO NOT EDIT.

package strategyservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	strategy "github.com/tankpanv/demo/recommend/kitex_gen/federation/recommend/strategy"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Recommend(ctx context.Context, req *strategy.StrategyRequest, callOptions ...callopt.Option) (r *strategy.StrategyResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kStrategyServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kStrategyServiceClient struct {
	*kClient
}

func (p *kStrategyServiceClient) Recommend(ctx context.Context, req *strategy.StrategyRequest, callOptions ...callopt.Option) (r *strategy.StrategyResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Recommend(ctx, req)
}
