// Code generated by Kitex v0.6.1. DO NOT EDIT.

package storepackerservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	packer "github.com/tankpanv/demo/packer/kitex_gen/wealth/stock/packer"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ArticleDatas(ctx context.Context, request *packer.ArticleDatasReq, callOptions ...callopt.Option) (r *packer.ArticleDatasResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kStorePackerServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kStorePackerServiceClient struct {
	*kClient
}

func (p *kStorePackerServiceClient) ArticleDatas(ctx context.Context, request *packer.ArticleDatasReq, callOptions ...callopt.Option) (r *packer.ArticleDatasResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ArticleDatas(ctx, request)
}
